Repository NullVoxPopuli/should-handle-link, pull requests merged in 2024-08, with the labels that each got.

#2 Setup release-plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  .gitignore
  CHANGELOG.md
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal

#1 exclude "download" & rel="external"
  index.js
Labels: enhancement

#4 Create LICENSE (MIT)
  LICENSE
Labels: documentation

#3 Update README with related projects and license
  README.md
Labels: documentation

#6 Add getAnchor
  README.md
  index.d.ts
  index.js
Labels: enhancement

#8 Add CI
  .eslintcache
  .eslintrc.cjs
  .github/workflows/ci.yml
  .prettierrc.cjs
  package.json
  pnpm-lock.yaml
  src/index.d.ts
  src/index.js
  tsconfig.json
Labels: internal

#10 Support <a> within SVG Documents
  src/index.js
Labels: bug
